# Generated by Django 5.0.4 on 2024-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productsmodel_category_productsmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'MyUser',
                'verbose_name_plural': 'MyUsers',
            },
        ),
    ]
